config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :pins do
    resources :comments
  end

  resources :comments do
    resources :comments
  end
  root 'pins#index'
  get 'home/index'
  get 'home/about'
  get 'users/edit'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  has_many :comments, as: :commentable 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
     devise_parameter_sanitizer.permit(:account_update, keys: [:name])
   end
 end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :find_commentable
  def new
     @comment = Comment.new
   end

   def create
     @comment = @commentable.comments.new comment_params

     if @comment.save
       redirect_to :back, notice: 'Your comment was successfully posted!'
     else
       redirect_to :back, notice: "Your comment wasn't posted!"
     end
   end

   private

   def comment_params
     params.require(:comment).permit(:body)
   end

   def find_commentable
     @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
     @commentable = Pin.find_by_id(params[:pin_id]) if params[:pin_id]
   end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]


 respond_to :html

 def index
   @pins = Pin.all
 end

 def show
   @pin = Pin.find(params[:id])
 end

 def new
   @pin = current_user.pins.build
 end

 def edit
 end

 def create
   @pin = current_user.pins.build(pin_params)
   if @pin.save
     redirect_to @pin, notice: 'Pin was successfully created.'
   else
     render action: 'new'
   end
 end

 def update
  if @pin.update(pin_params)
     redirect_to @pin, notice: 'Pin was successfully updated.'
   else
     render action: 'edit'
   end
 end

 def destroy
   @pin.destroy
   redirect_to pins_url
 end

 private
   def set_pin
     @pin = Pin.find(params[:id])
   end

   def pin_params
     params.require(:pin).permit(:description, :image,:name )
   end


 def correct_user
     @pin = current_user.pins.find_by(id: params[:id])
     redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/comments/_comment.html.erb
<li>
  <%= comment.body %> -
  <small>Submitted <%= time_ago_in_words(comment.created_at) %> ago</small>

  <%= form_for [comment, Comment.new] do |f| %>
      <%= f.text_area :body, placeholder: "Add a Reply" %><br/>
      <%= f.submit "Reply"  %>
      <% end %>

  <ul>
      <%= render partial: 'comments/comment', collection: comment.comments %>
  </ul>

</li>

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Maker Forum</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class= "active"><%= link_to 'Home', pins_path%> </li>
        <li ><%= link_to 'About us', home_about_path%> </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <%= link_to "New Pin",new_pin_path,class: "btn btn-default"  %>
        <%= link_to "List Pins",pins_path,class: "btn btn-default"  %>
        <%=link_to "Edit Profile", edit_user_registration_path,class:'btn btn-default btn-nav'%>
        <%=link_to "Logout", destroy_user_session_path,method: :delete, class:'btn btn-primary btn-nav'%>

        <% else %>
        <%=link_to "Login", new_user_session_path, class:'btn btn-default btn-nav'%>
        <%=link_to "Sign Up", new_user_registration_path, class:'btn btn-primary btn-nav'%>
        <% end %>


          </ul>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_jumbo.html.erb
<div class = "jumbotron">
<h1>Welcome!</h1>
<p>
  <%= link_to "Login",new_user_session_path,class: "btn btn-default"  %>
  <%= link_to "Join",new_user_registration_path,class: "btn btn-primary"  %>
</p>
</div>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MakerForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header'%>

    <div class = "container">
      <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pins/_form.html.erb
 <%= form_for @pin, html: { multipart: true } do |f| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :image %>
  <%= f.file_field :image, class: "form-control" %>
</div>


  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary"%>
  </div>
<% end %>
</div>

app/views/pins/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h1>Editing Pin</h1></div>
  <div class="panel-body">


<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>
</div>
</div>

app/views/pins/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading center">
    <%= render 'home/jumbo' unless user_signed_in? %>
  </div>
  <div class="panel-heading center">
    <h1>Pins</h1>
  </div>
  <div class="panel-body center">
    <p id="notice"><%= notice %></p>


    <div id="pins" class="transitions-enabled">
      <% @pins.each do |pin| %>
        <div class="box">
          <div class="panel panel-default">
            <div>
              <%= link_to image_tag(pin.image.url(:thumb)), pin %>
            </div>
            <div class="panel-body">
              <strong> <%= pin.user.name %></strong>
              </br>
              <div>  <%= pin.description%></div>
            </div>
            <% if pin.user == current_user%>
              <div class="panel-footer">
                <%= link_to 'Edit', edit_pin_path(pin), class: "btn btn-default" %>
                <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
</div>

 <div class="panel-footer">
   <%= link_to 'New Pin', new_pin_path ,class: "btn btn-primary "%>
</div>

app/views/pins/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h1>New Pin</h1></div>
  <div class="panel-body">
<%= render 'form', pin: @pin %>



 <div class="panel-footer">
<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
<div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">

  <div class="panel-heading center">
    <%= image_tag @pin.image.url(:medium) %></div>
    <div class="panel-body">
<p>
  <%= @pin.user.name %>
</br>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>
<%= link_to 'Back', pins_path, class: "btn btn-default" %>
<% if @pin.user == current_user%>
|
<%= link_to 'Edit', edit_pin_path(@pin), class: "btn btn-primary" %>

<%end%>
</div>
</div>
</div>
</div>
<h3>Comments</h3>

<%= form_for [@pin, Comment.new] do |f| %>
<%= f.text_area :body, placeholder: "Add a comment" %><br/>
<%= f.submit "Add Comment" %>
<% end %>

<ul>
  <%= render(partial: 'comments/comment', collection: @pin.comments) %>
</ul>